dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - gfortran
      - cmake
script:
  # Link gcc-6 and g++-6 to their standard commands
  - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-6
  #- export CXX=/usr/bin/g++-6
  - export CXX=/usr/bin/mpicxx
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version
  # Run your build commands next
  # Armadillo
  - cd TPLs/armadillo
  - cmake . -DCMAKE_INSTALL_PREFIX:PATH=.
  - make
  - make install
  # SuperLU 
  - cd ../../TPLs/superlu
  - cmake . -DCMAKE_INSTALL_PREFIX:PATH=.
  - make
  - make install
  # PETSc 
  - cd ../../TPLs/petsc
  - ./configure --with-fc=0
  - make PETSC_DIR=. PETSC_ARCH=arch-linux-c-debug all
  - make PETSC_DIR=. PETSC_ARCH=arch-linux-c-debug check
  # QuasiMolto 
  - cd ../../../
  - mkdir test-build
  - cd test-build
  - cmake -DCMAKE_BUILD_TYPE=Release ../QuasiMolto/
  - make all
  - make test
